#! /usr/bin/env bash

nomad_token=$1
nomad_address=$2
nomad_job_file_path=$3
config_file_path=$4

if [ -f "$nomad_job_file_path" ]; then
  export NOMAD_ADDR="$nomad_address"
  export NOMAD_TOKEN="$nomad_token"
  levant deploy -var-file "$config_file_path" "$nomad_job_file_path"
else
  echo "$nomad_job_file_path does not exist"
  exit 1
fi
